# Generated by Django 5.0.3 on 2024-03-30 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_value', models.FloatField(verbose_name='Market Value')),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('ft_week_high', models.FloatField(blank=True, null=True)),
                ('ft_week_low', models.FloatField(blank=True, null=True)),
                ('month_high', models.FloatField(blank=True, null=True)),
                ('month_low', models.FloatField(blank=True, null=True)),
                ('overall_high', models.FloatField(blank=True, null=True)),
                ('overall_low', models.FloatField(blank=True, null=True)),
                ('day_change', models.FloatField(default=0)),
                ('day_change_percentage', models.FloatField(default=0)),
                ('timestamp1', models.DateTimeField()),
                ('currency', models.CharField(max_length=10, verbose_name='Enter Currency')),
                ('ticker', models.ForeignKey(default=None, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='asset_price_relation', to='assets.asset')),
            ],
            options={
                'db_table': 'asset_pricing1',
                'unique_together': {('ticker', 'timestamp1')},
            },
        ),
    ]
